# ~/.config/genwall/config.toml
# rose-pine wallpaper generator

[General]
path = "~/.cache/genwall.png"
width = 2556
height = 1440
background = "#191724"
pallete = ["EB6F92", "F6C177", "EBCB8B", "31748F", "9CCFD8", "C4A7E7"]

[damascus]
enabled = false
line_num = 500
dot_radius = 2.0
line_length = 1500
noise_scale = 800
dot_step = 0.4

[voronoi]
enabled = false
num_points = 1000
stroke_width = 1.0
stroke_color = "#000000"

[spray]
enabled = true
num_points = 10000


